export const SET_NETWORK = 'SET_NETWORK';
export const GENERATE_MNEMONIC = 'GENERATE_MNEMONIC';      //产生助记词
export const WALLET_TRANSFER = 'WALLET_TRANSFER';           //钱包转账参数
export const TRANSACTION_DETAIL = 'TRANSACTION_DETAIL';     //交易记录信息
export const SET_WALLET_NAME = 'SET_WALLET_NAME'; //设置钱包名称
export const ADD_TOKEN = 'ADD_TOKEN';                       //添加token
export const REMOVE_TOKEN = 'REMOVE_TOKEN';                 //删除token
export const LOAD_TOKEN_BALANCE = 'LOAD_TOKEN_BALANCE';     //加载token余额
export const SET_TOTAL_ASSETS = 'SET_TOTAL_ASSETS';          //获取总资产 
export const SET_TRANSACTION_RECODER = 'SET_TRANSACTION_RECODER';          //获取交易记录
export const SET_COIN_BALANCE = 'SET_COIN_BALANCE';          //获取查看的token/eth余额
export const SET_LANGUAGE = 'SET_LANGUAGE';//设置语言
export const SET_MONETARY_UNIT = 'SET_MONETARY_UNIT'; //设置货币单位
export const SET_NEW_TRANSACTION = 'SET_NEW_TRANSACTION'; //设置未确认的交易
export const SET_FIRST_QR = 'SET_FIRST_QR';//设置第一次展示QR
export const SET_PIN_INFO = 'SET_PIN_INFO';//设置pin的信息
export const IS_NEW_WALLET = 'IS_NEW_WALLET';//是否刚导入/创建的钱包，用于home页判断是导入/创建进入Home页面还是直接进入Home的
export const SET_CONTACT_LIST = 'SET_CONTACT_LIST';//联系人列表
export const SET_ALL_TOKENS = 'SET_ALL_TOKENS';//获取所有的列表token
export const SET_TRANSFER_RECORD_LIST = 'SET_TRANSFER_RECORD_LIST';//转账记录列表
export const SET_ITC_WALLET_LIST = 'SET_ITC_WALLET_LIST';//itc钱包列表
export const SET_ETH_WALLET_LIST = 'SET_ETH_WALLET_LIST';//eth钱包列表
export const SET_CURRENT_WALLET = 'SET_CURRENT_WALLET';//当前正在使用的钱包
export const CREATE_WALLET_PARAM = 'CREATE_WALLET_PARAM';  //创建钱包参数

