export const TEST_WALLET = 'TEST_WALLET';
export const TEST_SELECT_API = 'TEST_SELECT_API';
export const SET_NETWORK = 'SET_NETWORK';
export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS';
export const GENERATE_MNEMONIC = 'GENERATE_MNEMONIC';      //产生助记词
export const WALLET_TRANSFER = 'WALLET_TRANSFER';           //钱包转账参数
export const TRANSACTION_DETAIL = 'TRANSACTION_DETAIL';     //交易记录信息
export const SET_WALLET_NAME = 'SET_WALLET_NAME'; //设置钱包名称
export const ADD_TOKEN = 'ADD_TOKEN';                       //添加token
export const REMOVE_TOKEN = 'REMOVE_TOKEN';                 //删除token
export const LOAD_TOKEN_BALANCE = 'LOAD_TOKEN_BALANCE';     //加载token余额
export const SET_TOTAL_ASSETS = 'SET_TOTAL_ASSETS';          //获取总资产 
export const SET_TRANSACTION_RECODER = 'SET_TRANSACTION_RECODER';          //获取交易记录
export const SET_COIN_BALANCE = 'SET_COIN_BALANCE';          //获取查看的token/eth余额
//export const SET_WALLET_PASSWORD_PROMPT = 'SET_WALLET_PASSWORD_PROMPT'; //设置钱包密码提示
